// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:0bcfa4a0-ff0b-4164-bb26-6602bfa49141",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_7vjy7Gfk8",
    "aws_user_pools_web_client_id": "18sqao1mu6vhn2j1c1748p8mgo"
};


export default awsmobile;
